name: CI-CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-app:1.0 ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:1.0
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:1.0 ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:1.0

    - uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VM_HOST }}
        username: ubuntu
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd means-stack-app-task
          docker compose pull
          docker compose up -d
